### ISSUE TITLE
Possible bug in disabled code

### ISSUE THREAD

**Issue by Wuodan** [Linesight-RL/linesight#38]
`make_untrained_iqn_network()` returns a `Tuple[Module, Module]` or in reality `Tuple[IQN_Network, IQN_Network]`.

But in trackmania_rl/multiprocess/learner_process.py:451, the Tuple is referenced, not one of the Modules.
`untrained_iqn_network = make_untrained_iqn_network(config_copy.use_jit)`

SonarLint (Java dev here) shows some warnings further below like:
_Unresolved attribute reference 'A_head' for class '(Module, Module)'_
which lead me to look into it.

I'm pretty certain the correct code would be:
`_, untrained_iqn_network = make_untrained_iqn_network(config_copy.use_jit)`
the other option being
`untrained_iqn_network, _ = make_untrained_iqn_network(config_copy.use_jit)`

**Comment by pb4git** [comment]
I think you are right.

A bit of history: periodic resets is a technique that was introduced in data-efficient reinforcement learning papers such as SPR or BBF (https://arxiv.org/abs/2305.19452).
We implemented the technique, but observed no improvement. Instead of removing the code, we just deactivated it.

The make_untrained_iqn_network() function was modified after deactivating periodic resets, and it seems we never caught this problem.

I can not test the code right now. I will merge your request as soon as I have tested the code.

Thanks!

**Comment by Wuodan** [comment]
Thanks for the feedback! I suspected that the code was inactive as I saw no problem before and no change after.

So far I just looked at the warnings (mostly from SonarLint) and this was the only thing that looked like a bug - compliments!
You requested small MRs with an issue each - so far I would create about 20 more such issues and MRs over the next few days.
And while I tested the result of all them rather well, I would not want to test each small change for hours and with several maps

Please let me know if you'd rather have all the commits in just 1 or a few MRs.
